#!/usr/bin/env node

/**
 * Regenerates public/sitemap.xml on every build.
 *
 * Emits every static route plus one entry per update post found under
 * content/updates/<slug>/index.md. The post's frontmatter `date` becomes
 * the URL's lastmod; folders starting with `_` (e.g. `_template/`) are
 * skipped.
 *
 * Environment overrides:
 *   SITE_ORIGIN   Full origin without trailing slash. Defaults to
 *                 "https://drcps.clinic".
 */

import { promises as fs } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const HERE   = path.dirname(fileURLToPath(import.meta.url));
const ROOT   = path.resolve(HERE, '..');
const OUT    = path.join(ROOT, 'public', 'sitemap.xml');
const ORIGIN = (process.env.SITE_ORIGIN || 'https://drcps.clinic').replace(/\/$/, '');
const TODAY  = new Date().toISOString().slice(0, 10);

// Static routes served by the SPA. Keep in sync with src/App.jsx.
const STATIC_ROUTES = [
  { path: '/',                             changefreq: 'weekly',  priority: '1.0' },
  { path: '/about',                        changefreq: 'monthly', priority: '0.8' },
  { path: '/services',                     changefreq: 'monthly', priority: '0.9' },
  { path: '/services/diabetes-clinic',     changefreq: 'monthly', priority: '0.9' },
  { path: '/services/general-physician',   changefreq: 'monthly', priority: '0.9' },
  { path: '/facilities',                   changefreq: 'monthly', priority: '0.7' },
  { path: '/gallery',                      changefreq: 'monthly', priority: '0.6' },
  { path: '/updates',                      changefreq: 'weekly',  priority: '0.7' },
  { path: '/resources',                    changefreq: 'monthly', priority: '0.7' },
  { path: '/contact',                      changefreq: 'monthly', priority: '0.9' },
];

// Extract the `date:` field from an index.md's YAML frontmatter without
// pulling in a parser. Falls back to today when the file has no date.
function extractDate(md) {
  const fm = md.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!fm) return TODAY;
  const dateLine = fm[1].split(/\r?\n/).find((l) => /^date\s*:/.test(l));
  if (!dateLine) return TODAY;
  const value = dateLine.replace(/^date\s*:\s*/, '').trim().replace(/^['"]|['"]$/g, '');
  return /^\d{4}-\d{2}-\d{2}/.test(value) ? value.slice(0, 10) : TODAY;
}

async function collectUpdatePosts() {
  const dir = path.join(ROOT, 'content', 'updates');
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return [];
  }

  const posts = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith('_')) continue; // _template/ etc.

    const mdPath = path.join(dir, entry.name, 'index.md');
    let md;
    try {
      md = await fs.readFile(mdPath, 'utf8');
    } catch {
      continue; // no index.md — not a post
    }
    posts.push({
      path: `/updates/${entry.name}`,
      lastmod: extractDate(md),
      changefreq: 'yearly',
      priority: '0.6',
    });
  }
  // Newest first so search engines see fresh URLs at the top.
  posts.sort((a, b) => (a.lastmod < b.lastmod ? 1 : -1));
  return posts;
}

function xmlEscape(s) {
  return String(s).replace(/[<>&'"]/g, (ch) => ({
    '<': '&lt;', '>': '&gt;', '&': '&amp;', "'": '&apos;', '"': '&quot;',
  }[ch]));
}

function renderUrl({ path: p, lastmod, changefreq, priority }) {
  const parts = [
    '  <url>',
    `    <loc>${xmlEscape(ORIGIN + p)}</loc>`,
    `    <lastmod>${lastmod}</lastmod>`,
  ];
  if (changefreq) parts.push(`    <changefreq>${changefreq}</changefreq>`);
  if (priority)   parts.push(`    <priority>${priority}</priority>`);
  parts.push('  </url>');
  return parts.join('\n');
}

async function main() {
  const postEntries = await collectUpdatePosts();
  const entries = [
    ...STATIC_ROUTES.map((r) => ({ ...r, lastmod: TODAY })),
    ...postEntries,
  ];

  const body = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<!-- Auto-generated by scripts/generate-sitemap.mjs on ${TODAY}. Do not edit by hand. -->`,
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...entries.map(renderUrl),
    '</urlset>',
    '',
  ].join('\n');

  await fs.mkdir(path.dirname(OUT), { recursive: true });
  await fs.writeFile(OUT, body, 'utf8');

  console.log(
    `sitemap: wrote ${entries.length} URLs (${STATIC_ROUTES.length} static + ${postEntries.length} posts) → ${path.relative(ROOT, OUT)}`,
  );
}

main().catch((err) => {
  console.error('sitemap: failed —', err);
  process.exit(1);
});
